MdePkg BaseMemoryLibSse2: Use movq for 64-bit move to xmm0
movd is intended for a 32-bit move, but we want to use a 64-bit move
of r8 into the low 64-bits of xmm0.

Without this change, after converting this code to NASM, this error
will be reported:
error: invalid combination of opcode and operands

Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: Jordan Justen <jordan.l.justen@intel.com>
Cc: Michael D Kinney <michael.d.kinney@intel.com>
Cc: Liming Gao <liming.gao@intel.com>